# Site
repository: Sung1Lim/Sung1Lim.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sungwon Lim (임성원)
title: Ph.D. Student in AI & NLP
email: wonirosoida33 [at] gmail [dot] com
website: github.com/Sung1Lim

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  Sung1Lim
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Sungwon Lim, and I am a Ph.D. student in Artificial Intelligence Convergence at Busan University of Foreign Studies, specializing in Natural Language Processing (NLP). I am passionate about developing intelligent systems that can understand and process human language effectively.
  
  My research focuses on:
  - Building machine learning models for text generation and comprehension.
  - Applying NLP techniques to create efficient language learning and evaluation systems.
  - Utilizing ontology mapping for structured and unstructured data integration.
  - Exploring the potential of large language models (LLMs) for language learners.

  I am most skilled in: <mark>Python</mark>, <mark>Deep Learning</mark>, and <mark>Natural Language Processing</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: NCSoft 초거대 언어 모델 학습용 프롬프트 데이터 구축 연구
        caption: March - May 2023
        sub_title: 과제 실무 담당자
        description: |
          초거대 언어 모델 학습을 위한 프롬프트 데이터 설계 및 품질 개선에 참여. 학습 환경 최적화에 기여.

      - layout: top-middle
        title: 블록체인 기반 STT 기술을 적용한 외국인 일자리 매칭 플랫폼 개발
        caption: August - December 2023
        sub_title: SW 실무 담당자
        description: |
          블록체인 및 음성 텍스트 변환(STT) 기술을 활용한 외국인 일자리 매칭 플랫폼 개발.

      - layout: top-middle
        title: 수산-식품 통합 빅데이터 구축에서 다층 온톨로지 매칭 기술 개발
        caption: April - November 2024
        sub_title: 과제 실무 담당자
        description: |
          정형 및 비정형 데이터 통합을 위한 다층 온톨로지 매칭 기술을 연구 및 개발.

      - layout: top-middle
        title: 블루푸드 데이터 해커톤
        caption: September - October 2024
        sub_title: 실무 책임자
        description: |
          부산외대와 링스업 공동 주최 해커톤을 기획 및 실무 관리.

      - layout: top-middle
        title: Lev art NFT 특허 출원을 위한 자연어처리 기술 자문
        caption: December 2024
        sub_title: 외부 용역
        description: |
          Lev art NFT 프로젝트의 특허 출원을 위해 자연어처리(NLP) 기술 자문을 제공.

  - title: Publications
    layout: list
    content:
      - layout: left
        title: "The Integration of Imported Data and Analysis of Import Volume Fluctuations using Machine Learning"
        caption: "2024 한국인공지능학회 하계학술대회"
        description: |
          기계 학습을 활용한 수입량 변동 분석 및 데이터 통합 기술에 대한 논문 발표.

      - layout: left
        title: "LLM을 활용한 한국어 학습자 대상 추론적 읽기 문제 자동 생성 시스템"
        caption: "2024 제36회 한글 및 한국어 정보처리 학술대회"
        description: |
          대형 언어 모델을 사용하여 한국어 학습자 대상 추론적 읽기 문제를 자동으로 생성하는 시스템에 관한 연구.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Busan University of Foreign Studies
        sub_title: Ph.D. in Artificial Intelligence Convergence
        caption: March 2023 - Present
        description: |
          부산외국어대학교 인공지능융합학과 박사과정 연구생으로, 자연어처리(NLP) 연구 수행. 주요 연구 분야는 대형 언어 모델(LLM) 활용, 데이터 처리 및 언어 학습 시스템 개발.

    - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Busan University of Foreign Studies
        caption: 2013.03 - 2019.02
        sub_title: Spanish Language and Literature
        description: |
          스페인어와 관련된 언어 및 문화학을 학습. 복수전공으로 한국어교육을 학습하였고 부전공으로 외교학과 학습

      - layout: left
        title: Busan University of Foreign Studies
        caption: 2020.03 - 2023.02
        sub_title: Department of Korean Language Education
        description: |
          한국어 교육학과 석사 졸업

      - layout: left
        title: Busan University of Foreign Studies
        caption: 2023.03 - Present
        sub_title: Ph.D. in Artificial Intelligence Convergence
        description: |
          부산외국어대학교 인공지능융합학과 박사과정 재학 중. 자연어처리 및 AI 기술 연구.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Besides that, I have other interests and hobbies such as:
      - Reading a book
      - Knitting


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
